### PR TITLE
Fix title position

### LINKED ISSUE #91: Title position is a bit off
The text `Password` is not in the middle.
image

### PR DESCRIPTION
**Pull request by outdoor2kode**
Fixes #91 

This PR fixes the position of the titles on the four main components.

## Screenshots

image
image
image
image

### CODE REVIEW

File: settings/src/script.js [hunk 1]
```diff
@@ -128,7 +128,6 @@ function Main( { userId } ) {
 		screenContent = (
 			<Card>
 				<CardHeader className="wporg-2fa__navigation" size="xSmall">
-					<Flex>
```
Comment (iandunn) [inline settings/src/script.js:131]: It looks like this was the only usage of `Flex`, so we can remove the `import` too.

**Review by iandunn — APPROVED** [review]
LGTM 👍🏻

File: settings/src/script.js (hunk 1 above)
Comment (outdoor2kode) [reply settings/src/script.js:131]: Ah, missed that, thanks.
